"""empty message

Revision ID: ebef9b40474e
Revises: 0408c6ffabb4
Create Date: 2020-12-09 09:36:26.489643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebef9b40474e'
down_revision = '0408c6ffabb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('comments', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('comments', 'deteled_at')
    op.add_column('diseases', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('diseases', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('diseases', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('diseases', 'deteled_at')
    op.add_column('donations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('donations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('donations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('donations', 'deteled_at')
    op.add_column('follows', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('follows', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('follows', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('follows', 'deteled_at')
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('relationships', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('relationships', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('relationships', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('relationships', 'deteled_at')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('users', 'deteled_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deteled_at', mysql.DATETIME(), nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('users', 'deleted_at')
    op.add_column('relationships', sa.Column('deteled_at', mysql.DATETIME(), nullable=True))
    op.alter_column('relationships', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('relationships', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('relationships', 'deleted_at')
    op.alter_column('posts', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('posts', 'deleted_at')
    op.add_column('follows', sa.Column('deteled_at', mysql.DATETIME(), nullable=True))
    op.alter_column('follows', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('follows', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('follows', 'deleted_at')
    op.add_column('donations', sa.Column('deteled_at', mysql.DATETIME(), nullable=True))
    op.alter_column('donations', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('donations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('donations', 'deleted_at')
    op.add_column('diseases', sa.Column('deteled_at', mysql.DATETIME(), nullable=True))
    op.alter_column('diseases', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('diseases', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('diseases', 'deleted_at')
    op.add_column('comments', sa.Column('deteled_at', mysql.DATETIME(), nullable=True))
    op.alter_column('comments', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('comments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('comments', 'deleted_at')
    # ### end Alembic commands ###
